wsgi/app/controle/urls.py
from django.conf.urls import patterns, include, url
# from django.views.generic import RedirectView
from django.contrib import admin
from django.contrib.auth import views as auth_views

admin.autodiscover()

urlpatterns = patterns('',
  url(r'^estoque/', include('controle.estoque.urls')),
  url(r'^venda/', include('controle.venda.urls')),
  url(r'^relatorio/', include('controle.relatorio.urls')),
  url(r'^admin/', include(admin.site.urls)),
  url(r'^accounts/login/$', auth_views.login),
  # url(r'^/', 'controle.geral.views.index'),
  # url(r'^caixa/', RedirectView.as_view(url='/venda/caixa')),
)

wsgi/app/controle/venda/urls.py
from django.conf.urls import patterns, url
from controle.venda import views

urlpatterns = patterns('',
    # url(r'^cupom$', views.gerar_cupom),

    url(r'^servico/gerar_cupom', views.gerar_cupom),
    url(r'^servico/fechar_cupom', views.fechar_cupom),
    url(r'^servico/consultar/(?P<codigo_produto>\d+)/$', views.consultar_item),
    url(r'^servico/adicionar/(?P<quantidade>\d+)/(?P<codigo_produto>\d+)/$', views.adicionar_item),
    url(r'^servico/cancelar/item/(?P<ordem>\d+)/$', views.cancelar_item),
    url(r'^servico/cancelar/cupom/(?P<numero>\d+)/$', views.cancelar_cupom),
    url(r'^servico/fechar_caixa', views.fechar_caixa),

    url(r'^impressao/cupom/(?P<numero>\d+)/$', views.impressao_cupom),
    url(r'^impressao/caixa/(?P<id>\d+)/$', views.impressao_caixa),
    
    url(r'^caixa/fechar', views.formulario_fechar_caixa),
    url(r'^sessao_caixa', views.sessao_caixa),
    url(r'^caixa$', views.caixa, name='caixa'),
)

wsgi/app/controle/venda/models.py
 #!/usr/bin/python
 # -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from controle.estoque.models import Loja, ProdutoPreco
from django.utils.html import format_html
from decimal import Decimal


class Caixa(models.Model):
	usuario = models.ForeignKey(User)
	loja = models.ForeignKey(Loja)
	fundo_caixa_inicial = models.DecimalField(verbose_name="Fundo inicial", max_digits=5, decimal_places=2, blank=False)
	fundo_caixa_final = models.DecimalField(verbose_name="Fundo final", max_digits=5, decimal_places=2, null=True, blank=True)
	valor_despesa = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=False)
	valor_consumo_interno = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
	valor_vendas = models.DecimalField(verbose_name="Total vendido", max_digits=5, decimal_places=2, null=True, blank=False)
	valor_entregue = models.DecimalField(verbose_name="Total em Caixa", max_digits=5, decimal_places=2, null=True, blank=False)
	valor_final = models.DecimalField(verbose_name="Total Caixa", max_digits=5, decimal_places=2, null=True, blank=False)
	data_inicial = models.DateTimeField(verbose_name="Data abertura", auto_now_add=True)
	data_final = models.DateTimeField(verbose_name="Data fechamento", null=True, blank=True)
	data_atualizacao = models.DateTimeField(auto_now=True)

	def extrato_completo(self):
		return format_html(u'<a href="/relatorio/caixa/{0}/" target="_blank">detalhamento</a>', self.id)

	def extrato_caixa(self):
		if self.data_final == None:
			return ''
		else:
			return format_html(u'<a href="/venda/impressao/caixa/{0}/" target="_blank">fechamento</a>', self.id)			

	def calcular_fechamento(self):
		self.valor_final = self.valor_entregue - (self.valor_despesa + self.fundo_caixa_final)
		self.save()
		self.loja.fundo_de_caixa = self.fundo_caixa_final
		self.loja.save()

	def calcular_total_vendas(self):
		self.valor_vendas = 0
		for cupom in self.cupons():
			self.valor_vendas += cupom.valor_total

	def calcular_total_vendedor(self):
		if (self.valor_entregue - self.valor_vendas) <= 0:
			self.valor_final = (self.valor_vendas - self.fundo_caixa_final)
		else: 
			self.valor_final = (self.valor_entregue - self.fundo_caixa_final)
		self.valor_final -= self.valor_despesa

	def cupons(self):
		return Cupom.objects.filter(caixa=self, pago=True)

	def cupons_pagos(self):
		Cupom.objects.filter(caixa=self, cancelado=False, pago=True)
	
	def cupons_cancelados(self):
		Cupom.objects.filter(caixa=self, cancelado=True)

	def __unicode__(self):
		return "%s - %d" % (self.loja.nome, self.id)


class Cupom(models.Model):
	caixa = models.ForeignKey(Caixa)
	total_itens = models.PositiveIntegerField(default=0, null=True)
	valor_total = models.DecimalField(max_digits=5, decimal_places=2, blank=True, default=0)
	valor_desconto = models.DecimalField(max_digits=5, decimal_places=2, blank=True, default=0)
	data_cadastro = models.DateTimeField(auto_now_add=True)
	data_atualizacao = models.DateTimeField(auto_now=True)
	cancelado = models.BooleanField(default=False)
	pago = models.BooleanField(default=False)

	def itens_todos(self):
		return Item.objects.filter(cupom=self)

	def itens_validos(self):
		return Item.objects.filter(cupom=self, cancelado=False)

	def cancelar(self):
		itens = Item.objects.filter(cupom=self)
		for item in itens:
			if not item.cancelado:
				item.cancelar()
		self.cancelado = True
		self.save()

	def adicionar(self, item):
		self.total_itens += 1
		self.valor_total += Decimal(item.preco_total)
		self.save()

	def remover(self, item):
		self.total_itens -= 1
		self.valor_total -= Decimal(item.preco_total)
		self.save()

	def finalizar(self):
		self.pago = True
		self.save()

	def __unicode__(self):
		return "%0*d" % (6, self.id)


class Item(models.Model):
	cupom = models.ForeignKey(Cupom)
	produto_preco = models.ForeignKey(ProdutoPreco)
	quantidade =  models.PositiveIntegerField()
	preco_unidade = models.DecimalField(max_digits=5, decimal_places=2)
	preco_total = models.DecimalField(max_digits=5, decimal_places=2)
	cancelado = models.BooleanField(default=False)

	def cancelar(self):
		self.produto_preco.devolver(self.quantidade)
		self.cancelado = True
		self.save()

	def __unicode__(self):
		return self.produto_preco.produto_venda.nome

wsgi/app/controle/venda/forms.py
# from django import forms
from django.forms import ModelForm
# from controle.estoque.models import Loja
from controle.venda.models import Caixa


class CaixaFinalForm(ModelForm):
	class Meta:
		model = Caixa
		fields = ['fundo_caixa_final', 'valor_despesa', 'valor_consumo_interno', 'valor_entregue']

	# def clean_fundo_caixa_final(self):
	# 	print "xxxxxxx"

class CaixaInicialForm(ModelForm):
	class Meta:
		model = Caixa
		fields = ['loja', 'fundo_caixa_inicial']

wsgi/app/controle/venda/views.py
 # -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from controle.estoque.models import ProdutoPreco, Loja
from controle.venda.models import Caixa, Cupom, Item
from controle.venda.forms import CaixaInicialForm, CaixaFinalForm
from django.core import serializers
from decimal import Decimal
from datetime import datetime
import json


@login_required
def gerar_cupom(request):
	# https://docs.djangoproject.com/en/dev/topics/auth/default/#auth-web-requests
	# usuario = request.user
	caixa = Caixa.objects.get(pk=request.session['caixa'])
	cupom, novo_cupom = Cupom.objects.get_or_create(caixa=caixa, pago=False)
	response = {}
	response['cupom'] = cupom.id
	request.session['cupom'] = cupom.id
	return HttpResponse(json.dumps(response), content_type = 'application/json')

@login_required
def fechar_cupom(request):
	cupom = Cupom.objects.get(pk=request.session['cupom'])
	cupom.finalizar()
	cupom_json = serializers.serialize("json", [cupom])
	return HttpResponse(cupom_json, content_type='json')

@login_required
def consultar_item(request, codigo_produto):
	response = {}
	try:
		loja = Loja.objects.get(pk=request.session['loja'])
		produto_preco = ProdutoPreco.objects.get(produto_venda__codigo=codigo_produto, loja=loja)

		response['produto'] = produto_preco.produto_venda.nome
		response['quantidade'] = 1
		response['valor_unidade'] = float(produto_preco.preco_loja)
		response['valor_total'] = response['valor_unidade']

	except ProdutoPreco.DoesNotExist:
		response['erro'] = 'preco do produto nao encontrado'

	return HttpResponse(json.dumps(response), content_type = 'application/json')

@login_required
def adicionar_item(request, quantidade, codigo_produto):
	response = {}
	quantidade = int(quantidade)
	loja = Loja.objects.get(pk=request.session['loja'])
	try:
		cupom = Cupom.objects.get(pk=request.session['cupom'])
		produto_preco = ProdutoPreco.objects.get(produto_venda__codigo=codigo_produto, loja=loja)

		produto_preco.consumir(quantidade)
		response['produto'] = produto_preco.produto_venda.nome
		response['quantidade'] = quantidade
		response['valor_unidade'] = float(produto_preco.preco_loja)
		response['valor_total'] = float(produto_preco.preco_loja * quantidade)

		item = Item.objects.create(produto_preco=produto_preco, cupom=cupom, quantidade=quantidade, preco_unidade=str(response['valor_unidade']), preco_total=str(response['valor_total']))
		cupom.adicionar(item)
		response['cupom_total'] = float(cupom.valor_total)

	except ProdutoPreco.DoesNotExist:
		response['erro'] = 'preco do produto nao encontrado'
	# except Exception, e:
	# 	response['erro'] = 'problema interno'
		
	return HttpResponse(json.dumps(response), content_type = 'application/json')

@login_required
def cancelar_item(request, ordem):
	response = {}
	cupom = Cupom.objects.get(pk=request.session['cupom'])
	itens = cupom.itens_todos()
	item = itens[int(ordem)-1]
	if not item.cancelado:
		item.cancelar();
		cupom.remover(item)
	response['cupom_total'] = float(cupom.valor_total)
	return HttpResponse(json.dumps(response), content_type = 'application/json')

@login_required
def cancelar_cupom(request, numero):
	response = {}
	cupom = get_object_or_404(Cupom, pk=numero, caixa__id=request.session['caixa'], pago=True, cancelado=False)
	cupom.cancelar()
	return HttpResponse(json.dumps(response), content_type = 'application/json')

@login_required
def impressao_cupom(request, numero):
	cupom = get_object_or_404(Cupom, pk=numero, pago=True)
	return render(request, 'impressao_cupom.html', {"cupom": cupom})

@login_required
def impressao_caixa(request, id):
	caixa = get_object_or_404(Caixa, pk=id)
	if caixa.data_final is None:
		return caixa(request)
	elif caixa.valor_final is None:
		return fechar_caixa(request)
	caixa.calcular_total_vendedor()
	caixa.save()
	return render(request, 'impressao_caixa.html', {
		"caixa": caixa,
		"saldo_vendedor": (caixa.valor_entregue - caixa.valor_despesa - (caixa.valor_vendas + caixa.fundo_caixa_inicial))
	})

@login_required
def sessao_caixa(request):
	form = CaixaInicialForm(request.POST)
	if form.is_valid():
		caixa_aberto = Caixa.objects.filter(usuario=request.user, valor_final=None).last()
		if caixa_aberto:
			print "CAIXA ABERTO > sessao_caixa()"
			request.session['loja'] = caixa_aberto.loja.id
			request.session['caixa'] = caixa_aberto.id
		else:
			loja = Loja.objects.get(pk = int(form.data['loja']))
			caixa = Caixa.objects.create(usuario=request.user, loja=loja, fundo_caixa_inicial=form.data['fundo_caixa_inicial'])
			request.session['loja'] = loja.id
			request.session['caixa'] = caixa.id
		return HttpResponseRedirect('/venda/caixa')
	else:
		return abrir_caixa(request, form)

@login_required
def fechar_caixa(request):
	caixa = Caixa.objects.get(pk=request.session['caixa'])
	if caixa.data_final == None:
		caixa.calcular_total_vendas()
		caixa.data_final = datetime.now()
		caixa.save()
	return HttpResponseRedirect('/venda/caixa/fechar')

@login_required
def formulario_fechar_caixa(request):
	if not request.session.has_key('caixa'):
		return HttpResponseRedirect('/venda/caixa')
	caixa = Caixa.objects.get(pk=request.session['caixa'])
	if request.POST:
		form = CaixaFinalForm(request.POST)
		if form.is_valid():
			caixa.valor_entregue = Decimal(form.data['valor_entregue'])
			caixa.fundo_caixa_final = Decimal(form.data['fundo_caixa_final'])
			caixa.valor_despesa = Decimal(form.data['valor_despesa'])
			caixa.calcular_fechamento()

			request.session.pop('loja')
			request.session.pop('caixa')
			request.session.pop('cupom')
			return HttpResponseRedirect('/venda/impressao/caixa/%d' % caixa.id)
		else:
			return render(request, 'caixa_form_fechar.html', {"form": form})

	form = CaixaFinalForm(instance=caixa)
	return render(request, 'caixa_form_fechar.html', {"form": form, "caixa": caixa})

@login_required
def abrir_caixa(request, form = None):
	caixa_aberto = Caixa.objects.filter(usuario=request.user, valor_final=None).last()
	if caixa_aberto:
		print "CAIXA ABERTO > abrir_caixa()"
		request.session['loja'] = caixa_aberto.loja.id
		request.session['caixa'] = caixa_aberto.id
		request.session['cupom'] = Cupom.objects.filter(caixa=caixa_aberto).last().id
		return HttpResponseRedirect('/venda/caixa')	
	return render(request, 'caixa_form_abrir.html', {"form": form})

@login_required
def caixa(request):
	if not request.session.has_key('loja') or not request.session.has_key('caixa'):
		form = CaixaInicialForm()
		return abrir_caixa(request, form)
	
	if request.session.has_key('cupom'):
		cupom = Cupom.objects.get(pk=request.session['cupom'])
	else:
		cupom = None

	return render(request, 'caixa.html', {"cupom": cupom})

wsgi/app/controle/venda/templates/caixa.html
{% extends "base.html" %}
{% load humanize %}

{% block content %}
<div class="linha black" id="logo">
	<div class="logo-imagem fonte-grande">Logo Gostosinho</div>
</div>
<div class="linha blue" id="caixa">
	<div class="tamanho-50 red">
		<div class="linha" id="visor">
			<p>nome produto</p>
			<p>quantidade # valor</p>
		</div>

		<div class="linha">
			<input name="quantidade" id="qtd" value="1" type="text">
			<form method="get" id="form_pesquisa">
				<input name="codigo" id="codigo_barra" placeholder="insira o código do produtos" autocomplete=off class="campo-input">
			</form>
		</div>

		<div class="linha" id="lista_itens">
			<ul class="{% if item.cancelado %}item-cancelado{% endif %}">
			    <li class="id"></li>
			    <li class="produto">PRODUTO</li>
			    <li class="quantidade">QTD</li>
			    <li class="valor-unidade">V. UNID</li>
			    <li class="valor-total">V. TOTAL</li>
			</ul>
			{% for item in cupom.itens_todos %}
				<ul class="{% if item.cancelado %}item-cancelado{% endif %}">
				    <li class="id">#{{ forloop.counter }}</li>
				    <li class="produto">{{ item.produto_preco.produto_venda.nome }}</li>
				    <li class="quantidade">{{ item.quantidade }}</li>
				    <li class="valor-unidade">{{ item.preco_unidade|floatformat:"2"|intcomma }}</li>
				    <li class="valor-total">{{ item.preco_total|floatformat:"2"|intcomma }}</li>
				</ul>
			{% endfor %}
		</div>

		<div class="linha linha-total fonte-grande">TOTAL A PAGAR
			<input name="valor_a_pagar" id="total_cupom" placeholder="0,00" value="{{cupom.valor_total|floatformat:'2'|intcomma }}" readonly="text">
			<input name="valor_pago" id="valor_pago" placeholder="0,00" value="" readonly="readonly" type="hidden">
		</div>
		<!-- <div class="linha linha-total fonte-grande">TROCO
			<input name="valor_troco" id="valor_troco" placeholder="0,00" value="" readonly="readonly">
		</div> -->
	</div>
	<div class="tamanho-50 black">
		<div class="linha">
			<div style="width:94%; height: 200px; background: #888; margin: 0 3%;"></div>
		</div>
		<div class="linha">
			<button id="botao-consultar-item" class="botao linha">consultar item</button>
		</div>
		<div class="linha">
			<button id="botao-alterar-quantidade" class="botao linha tamanho-50">alterar quantidade</button>
			<button id="botao-cancelar-item" class="botao linha tamanho-50">cancelar item</button>
		</div>
		<div class="linha">
			<button id="botao-fechar-cupom" class="botao linha tamanho-50">fechar cupom</button>
			<button id="botao-cancelar-cupom" class="botao linha tamanho-50">cancelar cupom</button>
		</div>
		<div class="linha">
			<button id="botao-fechar-caixa" class="botao linha">fechar caixa</button>
		</div>
	</div>
</div>
{% endblock %}

wsgi/app/controle/venda/templates/caixa_form_abrir.html
{% extends "base_bootstrap.html" %}

{% block content %}

{% if form.errors %}{% endif %}

{{ form.loja.errors }}
{{ form.fundo_caixa_inicial.errors }}

	<h2>Abertura do Caixa</h2>

	<form role="form" action="/venda/sessao_caixa" method="post">
		{% csrf_token %}
	  <div class="form-group input-group-lg">
	    <label for="exampleInputEmail1">{{ form.loja.label_tag }}</label>
	    <select id="id_loja" name="loja" class="form-control input-lg">
			{% for id, loja in form.fields.loja.choices %}
				<option value="{{id}}">{{loja|upper}}</option>
			{% endfor %}
		</select>
	  </div>
	  <div class="form-group">
	  	<label for="exampleInputPassword1">{{ form.fundo_caixa_inicial.label_tag }}</label>
	    <div class="input-group input-group-lg">
			  <span class="input-group-addon">R$</span>
			  <input type="text" class="form-control" name="fundo_caixa_inicial" id="id_fundo_caixa_inicial">
			  <span class="input-group-addon">,00</span>
			</div>
	  </div>

	  <button type="submit" class="btn btn-lg btn-primary btn-block">abrir caixa</button>
	</form>

{% endblock %}

wsgi/app/controle/venda/templates/caixa_form_fechar.html
{% extends "base_bootstrap.html" %}

{% block content %}

{% if form.errors %}{% endif %}

{{ form.valor_entregue.errors }}
{{ form.fundo_caixa_final.errors }}
{{ form.valor_despesa.errors }}

	<h2>Fechamento do Caixa</h2>

	<form role="form" action="/venda/caixa/fechar" method="post">
		{% csrf_token %}
	  <div class="form-group">
	  	<label for="id_valor_entregue">{{ form.valor_entregue.label_tag }}</label>
	    <div class="input-group input-group-lg">
			  <span class="input-group-addon">R$</span>
			  <input type="text" class="form-control" name="valor_entregue" id="id_valor_entregue">
			</div>
	  </div>
	  <div class="form-group">
	  	<label for="id_fundo_caixa_final">{{ form.fundo_caixa_final.label_tag }}</label>
	    <div class="input-group input-group-lg">
			  <span class="input-group-addon">R$</span>
			  <input type="text" class="form-control" name="fundo_caixa_final" id="id_fundo_caixa_final">
			</div>
	  </div>
	  <div class="form-group">
	  	<label for="id_valor_despesa">{{ form.valor_despesa.label_tag }}</label>
	    <div class="input-group input-group-lg">
			  <span class="input-group-addon">R$</span>
			  <input type="text" class="form-control" name="valor_despesa" id="id_valor_despesa">
			</div>
	  </div>

	  <button type="submit" class="btn btn-lg btn-primary btn-block">fechar caixa</button>
	</form>

{% endblock %}

wsgi/app/controle/venda/templates/impressao_caixa.html
{% extends "base_bootstrap.html" %}
{% load humanize %}

{% block content %}

{% if form.errors %}{% endif %}

	<h2>Extrato do Caixa: {{caixa.loja.nome}}</h2>

	<blockquote>
	  <p>{{caixa.usuario}}, verifique os valores do fechamento.</p>
	</blockquote>

	<dl class="dl-horizontal">
	  <dt>Data abertura</dt>
	  <dd>{{caixa.data_inicial}}</dd>
	</dl>

	<dl class="dl-horizontal">
	  <dt>Dinheiro do caixa</dt>
	  <dd>R$ {{caixa.valor_entregue|floatformat:"2"|intcomma}}</dd>
	</dl>
	<dl class="dl-horizontal">
	  <dt>Fundo de entrada</dt>
	  <dd>R$ {{caixa.fundo_caixa_inicial|floatformat:"2"|intcomma}} (+)</dd>
	</dl>
	<dl class="dl-horizontal">
	  <dt>Total em cupons</dt>
	  <dd class="">R$ {{caixa.valor_vendas|floatformat:"2"|intcomma}} (+)</dd>
	</dl>
	<dl class="dl-horizontal">
	  <dt>Despesas</dt>
	  <dd>R$ {{caixa.valor_despesa|floatformat:"2"|intcomma}} (-)</dd>
	</dl>
	<dl class="dl-horizontal {% if saldo_vendedor > 0 %}text-success{% elif saldo_vendedor < 0 %}text-danger{% endif %}">
	  <dt>SALDO</dt>
	  <dd>R$ {{saldo_vendedor|floatformat:"2"|intcomma}}</dd>
	</dl>

	<dl class="dl-horizontal">
	  <dt>Fundo fechamento</dt>
	  <dd>R$ {{caixa.fundo_caixa_final|floatformat:"2"|intcomma}}</dd>
	</dl>

	<dl class="dl-horizontal">
	  <dt>ENTREGAR</dt>
	  <dd>R$ {{caixa.valor_final|floatformat:"2"|intcomma}}</dd>
	</dl>
	<dl class="dl-horizontal">
	  <dt>Data fechamento</dt>
	  <dd>{{caixa.data_final}}</dd>
	</dl>

{% endblock %}

wsgi/app/controle/venda/templates/impressao_cupom.html
<p>Caixa: {{cupom.caixa}} </p>
<p>Numero: {{cupom.id}} </p>

<ul>
{% for item in cupom.itens_validos %}
	<li>{{item.preco_produto.produto.nome}} = R$ {{item.preco_total}}</li>
{% endfor %}
</ul>

<p>Total: {{cupom.valor_total}}</p>